### ISSUE TITLE
ERROR: "python2 Qlearning.py --mode 1"

### ISSUE THREAD

**Issue by fentuoli** [allenlsj/physics_world_rl#2]
When I use commend "python2 Qlearning.py --mode 1" to train a q-value function, it produces error "TypeError: __init__() takes exactly 9 arguments (8 given)". I find that in Qlearning.py, the last line is " new_env = physic_env(cond, mass_list, force_list, init_mouse, T, args.mode, prior)" , it misses the last parameter: reward_stop. When I try to add this parameter, it produces another error.So how to solve this problem correctly? I'm waiting for your answer eagerly!

**Comment by allenlsj** [comment]
What error does it give when you add reward_stop? Can you run Qagent.py or RQN.py without error? reward_stop has been explicitly added into the initialization arguments of the environment in Qagent.py and RQN.py. You can modify it in simulator/config.py

**Comment by fentuoli** [comment]
> What error does it give when you add reward_stop? Can you run Qagent.py or RQN.py without error? reward_stop has been explicitly added into the initialization arguments of the environment in Qagent.py and RQN.py. You can modify it in simulator/config.py

When I added reward_stop in Qlearning.py explicitly, it gave the following error: 
"File "../simulator/environment.py", line 29, in __init__
    self.cond = cond[np.random.randint(len(cond))]
KeyError: 2"
I don't know how to solve this error.
I can run Qagent.py and RQN.py without error, but I don't know how long it will take for there isn't any information about time.So could you please tell me how much time will I spend on running Qagent.py and RQN.py?

**Comment by allenlsj** [comment]
It depends on the computing resource you are using and the number of epochs you set. We did the experiment 2 years ago. If my memory is correct, you should expect roughly 3-6 hrs running Qagent.py or RQN.py on a single CPU with standard memory size. 

You can also switch to the simulator_opt branch, where we optimized a bit on the simulation process. You can expect ~30% speed up if running on that branch. Hope this helps.

**Comment by fentuoli** [comment]
> It depends on the computing resource you are using and the number of epochs you set. We did the experiment 2 years ago. If my memory is correct, you should expect roughly 3-6 hrs running Qagent.py or RQN.py on a single CPU with standard memory size.
> 
> You can also switch to the simulator_opt branch, where we optimized a bit on the simulation process. You can expect ~30% speed up if running on that branch. Hope this helps.

Thanks a lot. And could you give me some advice on how to solve the error causing by the missing parameter "reward_stop"? I am waiting for your reply! Thank you again!

**Comment by allenlsj** [comment]
Based on the error message, it seems that the issue is related to the difference between 'cond' and 'train_cond' in config.py. Can you replace 'cond' with 'train_cond' as the initialization parameter for the environment in Qlearning.py, and see if that works?

**Comment by fentuoli** [comment]
> Based on the error message, it seems that the issue is related to the difference between 'cond' and 'train_cond' in config.py. Can you replace 'cond' with 'train_cond' as the initialization parameter for the environment in Qlearning.py, and see if that works?

After I replaced 'cond' with 'train_cond', another error appeared :)

Traceback (most recent call last):
  File "Qlearning.py", line 167, in <module>
    train_loop(args)
  File "Qlearning.py", line 105, in train_loop
    results = [train_iteration(t_max=1000, epsilon=epsilon, train=True) for t in range(args.sessions)]
  File "Qlearning.py", line 80, in train_iteration
    s_next, r, is_done = new_env.step(a)
ValueError: too many values to unpack

Do you have some advice? I'm really sorry for disturbing you again and again, and I really appreciate your patience !

**Comment by allenlsj** [comment]
Can you try to replace s_next, r, is_done = new_env.step(a) with s_next, r, is_done, r_others = new_env.step(a)? 

Sorry for the continuous bugs you ran into. We wrote Qlearning.py and finished its experiment first, and then did more developments on the simulator later. As far as I remember, Qagent.py and RQN.py were developed after the simulator was all set, and we did not go back to Qlearning.py to keep it updated with the modifications. What I can suggest, is that you can closely follow the use cases of the simulator in either Qagent.py or RQN.py if you run into other issues in Qlearning.py. And feel free to make a PR if you fix them!

**Comment by fentuoli** [comment]
> Can you try to replace s_next, r, is_done = new_env.step(a) with s_next, r, is_done, r_others = new_env.step(a)?
> 
> Sorry for the continuous bugs you ran into. We wrote Qlearning.py and finished its experiment first, and then did more developments on the simulator later. As far as I remember, Qagent.py and RQN.py were developed after the simulator was all set, and we did not go back to Qlearning.py to keep it updated with the modifications. What I can suggest, is that you can closely follow the use cases of the simulator in either Qagent.py or RQN.py if you run into other issues in Qlearning.py. And feel free to make a PR if you fix them!

After I did this modification, Qlearning.py could be ran smoothly. Thank you very much! I will make a PR when I finish training.
